-- O formulário de avaliação não manda id_avaliacao, quem gera é o banco.
-- Só rode isso se o insert reclamar de "null value in column id_avaliacao"
-- (ou seja, se a coluna foi criada como integer comum, sem identity/serial).

alter table avaliacao
    alter column id_avaliacao add generated by default as identity;

-- Se a tabela já tiver linhas, o contador precisa começar depois do maior id:
-- select setval(pg_get_serial_sequence('avaliacao', 'id_avaliacao'),
--               coalesce((select max(id_avaliacao) from avaliacao), 0) + 1, false);
